#!/usr/bin/env bash
################################################################################
# ForL0 offline app launcher
#
# One command on the offline server:
#   bash ./forl0-offline-app.sh
# Default Flink installation: $HOME/flink_home
#
# It works in either layout:
#   1. full repository root
#   2. offline bundle root generated by docker/package_offline_bundle.sh
################################################################################

# Some operators habitually invoke scripts with `sh script.sh`, which ignores
# the Bash shebang and otherwise fails later with an opaque "bad substitution".
# Re-enter Bash before any Bash-only syntax is parsed.
if [ -z "${BASH_VERSION:-}" ]; then
    if command -v bash >/dev/null 2>&1; then
        exec bash "$0" "$@"
    fi
    echo "ERROR: this launcher requires bash, but bash was not found" >&2
    exit 1
fi

set -euo pipefail

LAUNCHER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="${FORL0_APP_ROOT:-${LAUNCHER_ROOT}}"
CONTROL_ROOT="${FORL0_CONTROL_ROOT:-${APP_ROOT}}"
L0_DETECTOR="${APP_ROOT}/docker/lib/l0_detector.sh"
if [[ ! -f "$L0_DETECTOR" ]]; then
    echo "ERROR: missing L0 detector: $L0_DETECTOR" >&2
    exit 1
fi
source "$L0_DETECTOR"
FLINK_DIR="${FLINK_HOME:-}"
INSTALL_DIR="${HOME}/forl0-runtime"
RESULTS_DIR="${APP_ROOT}/benchmark/results"
BACKEND="all"
QUERIES="q4,q5,q8,q9,q11,q18,q19,q20"
QUERIES_EXPLICIT=false
PRESSURE_SCENARIOS="forl0_tps_probe"
REPRO_WORKLOADS="all"
RUN_SMOKE=true
RUN_APPS=true
RUN_NEXMARK_PRESSURE=false
RUN_ASCEND_REPRO=false
RUN_REPORT=true
PROFILE_ARGS=(--no-profile)
SKIP_DOCKER_LOAD=false
KEEP_GOING=false
HAD_FAILURE=false
RESTART_CLUSTER=false
INITIAL_RESTART_CLUSTER=true
LIST_WORKLOADS=false
EXPECTED_TASKMANAGERS="${FORL0_EXPECTED_TASKMANAGERS:-2}"
EXPECTED_SLOTS="${FORL0_EXPECTED_SLOTS:-8}"
RUNNER_EXTRA_ARGS=()
REQUIRE_L0=true

ASCEND_REPRO_WORKLOADS=(
    "W01|wordcount_stateful_counter_p4_hashmap|WordCount stateful_counter_p4_probe median-of-3, HashMap baseline, isolated cluster"
    "W02|wordcount_stateful_counter_p4_forl0|WordCount stateful_counter_p4_probe median-of-3, ForL0 tuned config, isolated cluster"
    "N01|nexmark_q18_tps_hashmap|NexMark forl0_tps_probe q18, HashMap baseline, isolated cluster"
    "N02|nexmark_q18_tps_forl0|NexMark forl0_tps_probe q18, ForL0 stable config, isolated cluster"
    "N03|nexmark_q18_lateq_deep_hashmap|NexMark forl0_no_full_gc_lateq_deep q18, HashMap baseline, isolated cluster"
    "N04|nexmark_q18_lateq_deep_forl0|NexMark forl0_no_full_gc_lateq_deep q18, ForL0 tuned config, isolated cluster"
    "N05|nexmark_q19_tps_hashmap|NexMark forl0_tps_probe q19, HashMap supplementary comparison, isolated cluster"
    "N06|nexmark_q19_tps_forl0|NexMark forl0_tps_probe q19, ForL0 supplementary comparison, isolated cluster"
    "N07|nexmark_q20_lateq_deep_hashmap|NexMark forl0_no_full_gc_lateq_deep q20, HashMap high-pressure comparison, isolated cluster"
    "N08|nexmark_q20_lateq_deep_forl0|NexMark forl0_no_full_gc_lateq_deep q20, ForL0 high-pressure comparison, isolated cluster"
    "N09|nexmark_q9_allq_pressure_hashmap|NexMark forl0_no_full_gc_allq_pressure q9, HashMap CPU-efficiency comparison, isolated cluster"
    "N10|nexmark_q9_allq_pressure_forl0|NexMark forl0_no_full_gc_allq_pressure q9, ForL0 CPU-efficiency comparison, isolated cluster"
    "N11|nexmark_q4_pressure_hashmap|NexMark forl0_no_full_gc_pressure q4, HashMap high-pressure comparison, isolated cluster"
    "N12|nexmark_q4_pressure_forl0|NexMark forl0_no_full_gc_pressure q4, ForL0 high-pressure comparison, isolated cluster"
    "N13|nexmark_q3_extra_sql_hashmap|NexMark forl0_no_full_gc_extra_sql q3, HashMap extra SQL comparison, isolated cluster"
    "N14|nexmark_q3_extra_sql_forl0|NexMark forl0_no_full_gc_extra_sql q3, ForL0 extra SQL comparison, isolated cluster"
    "C01|client_contract_hashmap|Client usecase contract_baseline, HashMap baseline, isolated cluster"
    "C02|client_contract_forl0|Client usecase contract_baseline, ForL0, isolated cluster"
    "C03|client_forl0_optimized_hashmap|Client usecase forl0_optimized, HashMap baseline, isolated cluster"
    "C04|client_forl0_optimized_forl0|Client usecase forl0_optimized, ForL0 tuned config, isolated cluster"
    "C05|client_state_pressure_300k_hashmap|Client usecase state_pressure_300k, HashMap baseline, isolated cluster"
    "C06|client_state_pressure_300k_forl0|Client usecase state_pressure_300k, ForL0 tuned config, isolated cluster"
    "C07|client_scalar_ops64_batch_hashmap|Client scalar_state_probe_2m_ops64_batch, HashMap diagnostic pressure comparison, isolated cluster"
    "C08|client_scalar_ops64_batch_forl0|Client scalar_state_probe_2m_ops64_batch, ForL0 diagnostic pressure comparison, isolated cluster"
)

usage() {
    cat <<'EOF'
ForL0 offline app launcher

Usage:
  ./forl0-offline-app.sh [options]
  ./forl0-offline-app.sh /custom/path/to/flink [options]
  ./forl0-offline-app.sh --flink-home /custom/path/to/flink [options]

Common options:
  --flink-home PATH       Flink installation directory. Can also use FLINK_HOME.
                          Default: $HOME/flink_home
  --install-dir PATH      Runtime install dir when running from an offline bundle.
                          Default: ~/forl0-runtime
  --results-dir PATH      Benchmark output directory. Relative paths are resolved
                          from the launcher directory. Default: benchmark/results
  --backend NAME          all / forl0 / hashmap. Default: all
  --queries LIST          Override NexMark query list for pressure scenarios.
                          By default, each tuned pressure scenario uses its own
                          query list from benchmark.yaml; allq uses q4,q5,q8,q9,q11,q18,q19,q20.
  --pressure-scenarios LIST
                          Comma-separated NexMark pressure scenarios for --full.
                          Default: forl0_tps_probe. Deep no-Full-GC pressure
                          scenarios are opt-in because they can OOM 16GB TMs.
  --workloads LIST        Run selected numbered Ascend reproduction workloads.
                          Example: --workloads W01,W02,N01,N02,C01,C02
  --list-workloads        Print numbered Ascend reproduction workloads and exit.

Run modes:
  --smoke-only            Install + preflight + short client smoke test only.
  --apps-only             Install + preflight + contract apps only.
  --full                  Also run the configured NexMark throughput scenarios after apps.
  --pressure-only         Install + preflight + configured NexMark throughput scenarios only.
  --reproduce-ascend      Run the numbered Ascend reproduction suite.
  --report-only           Do not run experiments; regenerate HTML report only.
  --no-report             Do not generate the final HTML report.
  --with-profile          Enable default CPU profiling. Default is --no-profile.
  --profile MODE          Enable a specific profile mode, e.g. cpu/cache/uarch.

Operational options:
  --allow-simulation     Do not require real L0 hardware. Use only for local
                          dry-runs; offline L0 validation should omit this.
  --skip-docker-load      Do not import docker/images/eclipse-temurin-8-jre.tar*.
  --keep-going            Continue to report generation after a benchmark failure.
  --restart-cluster       Restart the benchmark Flink cluster before running.
  --no-initial-restart    Reuse an existing healthy Flink cluster. Not recommended
                          for real L0 validation because old containers may miss
                          L0 device/library mounts.
  --expected-taskmanagers N
                          Required registered TaskManager count before experiments.
                          Default: 2
  --expected-slots N      Required total slot count before experiments. Default: 8
  --runner-arg ARG        Pass one extra argument through to the benchmark runner.
                          Repeat for multiple arguments; use --runner-arg --foo=bar
                          for option-like values.
  -h, --help              Show this help.
EOF
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

info() {
    echo ""
    echo "==> $*"
}

print_python_wheel_recovery() {
    cat >&2 <<'EOF'

如果上面的错误包含 “Could not find a version that satisfies the requirement”，
说明离线 Python wheel 不完整或与服务器的 Linux 架构/Python 版本不匹配。

先在离线服务器确认目标信息：
  uname -m
  ./tools/python/bin/python3 --version

新版完整离线包自带与 wheels 匹配的可携带 Python。若 tools/python/bin/python3
不存在，说明使用了旧包或打包时跳过了 portable Python；请换用最新完整 Release，
不要在没有 Python 的离线机上继续调用 pip。
EOF
}

list_ascend_workloads() {
    printf "%-4s  %-36s  %s\n" "ID" "Name" "Description"
    printf "%-4s  %-36s  %s\n" "----" "------------------------------------" "-----------"
    local entry id name description
    for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
        IFS='|' read -r id name description <<< "$entry"
        printf "%-4s  %-36s  %s\n" "$id" "$name" "$description"
    done
}

workload_selected() {
    local id="$1"
    local requested token
    local -a selected_workloads
    requested="$(printf '%s' "$REPRO_WORKLOADS" | tr '[:lower:]' '[:upper:]')"
    [[ "$requested" == "ALL" ]] && return 0
    IFS=',' read -r -a selected_workloads <<< "$requested"
    for token in "${selected_workloads[@]}"; do
        token="$(printf '%s' "$token" | xargs)"
        [[ "$token" == "$id" ]] && return 0
    done
    return 1
}

validate_repro_workloads() {
    local requested token entry id found
    local -a selected_workloads
    requested="$(printf '%s' "$REPRO_WORKLOADS" | tr '[:lower:]' '[:upper:]')"
    [[ "$requested" == "ALL" ]] && return 0
    IFS=',' read -r -a selected_workloads <<< "$requested"
    for token in "${selected_workloads[@]}"; do
        token="$(printf '%s' "$token" | xargs)"
        [[ -n "$token" ]] || continue
        found=false
        for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
            IFS='|' read -r id _ <<< "$entry"
            if [[ "$id" == "$token" ]]; then
                found=true
                break
            fi
        done
        if [[ "$found" != "true" ]]; then
            echo "ERROR: unknown workload id: $token" >&2
            echo "" >&2
            list_ascend_workloads >&2
            exit 1
        fi
    done
}

workload_name() {
    local id="$1"
    local entry wid name description
    for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
        IFS='|' read -r wid name description <<< "$entry"
        if [[ "$wid" == "$id" ]]; then
            printf '%s' "$name"
            return 0
        fi
    done
    printf '%s' "$id"
}

run_ascend_workload() {
    local id="$1"
    local name
    name="$(workload_name "$id")"
    local args=()

    case "$id" in
        W01) args=(--test wordcount --scenario stateful_counter_p4_probe --backend hashmap) ;;
        W02) args=(--test wordcount --scenario stateful_counter_p4_probe --backend forl0) ;;
        N01) args=(--test nexmark --scenario forl0_tps_probe --query q18 --backend hashmap) ;;
        N02) args=(--test nexmark --scenario forl0_tps_probe --query q18 --backend forl0) ;;
        N03) args=(--test nexmark --scenario forl0_no_full_gc_lateq_deep --query q18 --backend hashmap) ;;
        N04) args=(--test nexmark --scenario forl0_no_full_gc_lateq_deep --query q18 --backend forl0) ;;
        N05) args=(--test nexmark --scenario forl0_tps_probe --query q19 --backend hashmap) ;;
        N06) args=(--test nexmark --scenario forl0_tps_probe --query q19 --backend forl0) ;;
        N07) args=(--test nexmark --scenario forl0_no_full_gc_lateq_deep --query q20 --backend hashmap) ;;
        N08) args=(--test nexmark --scenario forl0_no_full_gc_lateq_deep --query q20 --backend forl0) ;;
        N09) args=(--test nexmark --scenario forl0_no_full_gc_allq_pressure --query q9 --backend hashmap) ;;
        N10) args=(--test nexmark --scenario forl0_no_full_gc_allq_pressure --query q9 --backend forl0) ;;
        N11) args=(--test nexmark --scenario forl0_no_full_gc_pressure --query q4 --backend hashmap) ;;
        N12) args=(--test nexmark --scenario forl0_no_full_gc_pressure --query q4 --backend forl0) ;;
        N13) args=(--test nexmark --scenario forl0_no_full_gc_extra_sql --query q3 --backend hashmap) ;;
        N14) args=(--test nexmark --scenario forl0_no_full_gc_extra_sql --query q3 --backend forl0) ;;
        C01) args=(--test client_usecase --scenario contract_baseline --backend hashmap) ;;
        C02) args=(--test client_usecase --scenario contract_baseline --backend forl0) ;;
        C03) args=(--test client_usecase --scenario forl0_optimized --backend hashmap) ;;
        C04) args=(--test client_usecase --scenario forl0_optimized --backend forl0) ;;
        C05) args=(--test client_usecase --scenario state_pressure_300k --backend hashmap) ;;
        C06) args=(--test client_usecase --scenario state_pressure_300k --backend forl0) ;;
        C07) args=(--test client_usecase --scenario scalar_state_probe_2m_ops64_batch --backend hashmap) ;;
        C08) args=(--test client_usecase --scenario scalar_state_probe_2m_ops64_batch --backend forl0) ;;
        *) die "unknown Ascend reproduction workload id: $id" ;;
    esac

    run_or_handle_failure "Ascend reproduction ${id}: ${name}" \
        "$RUNNER" --offline "${args[@]}" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --flink-home)
            FLINK_DIR="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --results-dir)
            RESULTS_DIR="$2"
            shift 2
            ;;
        --backend)
            BACKEND="$2"
            shift 2
            ;;
        --queries)
            QUERIES="$2"
            QUERIES_EXPLICIT=true
            shift 2
            ;;
        --pressure-scenarios)
            PRESSURE_SCENARIOS="$2"
            shift 2
            ;;
        --workloads)
            REPRO_WORKLOADS="$2"
            RUN_ASCEND_REPRO=true
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            shift 2
            ;;
        --list-workloads)
            LIST_WORKLOADS=true
            shift
            ;;
        --smoke-only)
            RUN_SMOKE=true
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            shift
            ;;
        --apps-only)
            RUN_SMOKE=false
            RUN_APPS=true
            RUN_NEXMARK_PRESSURE=false
            shift
            ;;
        --full)
            RUN_SMOKE=true
            RUN_APPS=true
            RUN_NEXMARK_PRESSURE=true
            shift
            ;;
        --pressure-only)
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=true
            shift
            ;;
        --reproduce-ascend)
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            RUN_ASCEND_REPRO=true
            shift
            ;;
        --report-only)
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            RUN_REPORT=true
            shift
            ;;
        --no-report)
            RUN_REPORT=false
            shift
            ;;
        --with-profile)
            PROFILE_ARGS=(--profile cpu)
            shift
            ;;
        --profile)
            PROFILE_ARGS=(--profile "$2")
            shift 2
            ;;
        --skip-docker-load)
            SKIP_DOCKER_LOAD=true
            shift
            ;;
        --allow-simulation)
            REQUIRE_L0=false
            shift
            ;;
        --keep-going)
            KEEP_GOING=true
            shift
            ;;
        --restart-cluster)
            RESTART_CLUSTER=true
            shift
            ;;
        --no-initial-restart)
            INITIAL_RESTART_CLUSTER=false
            shift
            ;;
        --expected-taskmanagers)
            EXPECTED_TASKMANAGERS="$2"
            shift 2
            ;;
        --expected-slots)
            EXPECTED_SLOTS="$2"
            shift 2
            ;;
        --runner-arg)
            RUNNER_EXTRA_ARGS+=("$2")
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            if [[ "$1" != --* && -z "$FLINK_DIR" ]]; then
                FLINK_DIR="$1"
            else
                RUNNER_EXTRA_ARGS+=("$1")
            fi
            shift
            ;;
    esac
done

if [[ "$LIST_WORKLOADS" == "true" ]]; then
    list_ascend_workloads
    exit 0
fi

validate_repro_workloads

if [[ "$RUN_ASCEND_REPRO" == "true" ]]; then
    RESTART_CLUSTER=true
fi

case "$BACKEND" in
    all|forl0|hashmap) ;;
    *) die "--backend must be all, forl0, or hashmap: $BACKEND" ;;
esac

if [[ -z "$FLINK_DIR" ]]; then
    FLINK_DIR="${HOME}/flink_home"
fi
if [[ ! -x "$FLINK_DIR/bin/flink" ]]; then
    if ! compgen -G "${APP_ROOT}/tools/flink/flink-*-bin-scala_*.tgz" >/dev/null && \
       ! compgen -G "${APP_ROOT}/tools/flink/flink-*-bin-scala_*.tar.gz" >/dev/null; then
        die "FLINK_HOME is incomplete (${FLINK_DIR}/bin/flink missing) and the bundle has no Flink distribution"
    fi
    echo "WARN: ${FLINK_DIR}/bin/flink is missing; the bundled Flink distribution will be installed automatically."
fi
export FLINK_HOME="$FLINK_DIR"

find_first_existing_file() {
    local candidate
    for candidate in "$@"; do
        if [[ -f "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

check_l0_environment() {
    local failed=false

    forl0_detect_l0_environment || true

    info "Checking L0 hardware environment"
    forl0_print_l0_detection
    if [[ -z "$FORL0_L0_DEVICE_PATH" ]]; then
        failed=true
    fi
    if [[ -z "$FORL0_L0_LIBRARY_PATH" ]]; then
        failed=true
    fi
    if [[ -z "$FORL0_NUMA_LIBRARY_PATH" ]]; then
        failed=true
    fi

    export L0_DEVICE_HOST_PATH="$FORL0_L0_DEVICE_PATH"
    export L0_MEMPOOL_LIB_HOST_PATH="$FORL0_L0_LIBRARY_PATH"
    export NUMA_LIB_HOST_PATH="$FORL0_NUMA_LIBRARY_PATH"
    forl0_prepend_l0_library_path "$FORL0_L0_LIBRARY_PATH"

    if [[ "$failed" == "true" ]]; then
        if [[ "$REQUIRE_L0" == "true" ]]; then
            die "real L0 environment is required. Fix the missing items above, or use --allow-simulation only for local dry-runs."
        fi
        echo "WARN: L0 hardware is incomplete; continuing in simulation/dry-run mode because --allow-simulation was set."
    else
        echo "  result:      real L0 environment looks available"
    fi
}

check_l0_environment

detect_docker_cmd() {
    if docker ps >/dev/null 2>&1; then
        echo "docker"
        return 0
    fi
    if sudo -n docker ps >/dev/null 2>&1; then
        echo "sudo -n docker"
        return 0
    fi
    return 1
}

load_docker_image_if_present() {
    [[ "$SKIP_DOCKER_LOAD" == "false" ]] || return 0

    local docker_cmd
    docker_cmd="$(detect_docker_cmd || true)"
    if [[ -z "$docker_cmd" ]]; then
        echo "WARN: docker is unavailable for current user; standalone fallback may be used."
        return 0
    fi

    if $docker_cmd image inspect eclipse-temurin:8-jre >/dev/null 2>&1; then
        echo "Docker image already present: eclipse-temurin:8-jre"
        return 0
    fi

    local image_file=""
    for candidate in \
        "${APP_ROOT}/docker/images/eclipse-temurin-8-jre.tar.gz" \
        "${APP_ROOT}/docker/images/eclipse-temurin-8-jre.tar" \
        "${APP_ROOT}/eclipse-temurin-8-jre.tar.gz" \
        "${APP_ROOT}/eclipse-temurin-8-jre.tar"; do
        if [[ -f "$candidate" ]]; then
            image_file="$candidate"
            break
        fi
    done

    if [[ -n "$image_file" ]]; then
        info "Loading Docker image: $image_file"
        $docker_cmd load -i "$image_file"
    else
        echo "WARN: docker image is not present in bundle; docker_run.sh may fail offline."
    fi
}

run_or_handle_failure() {
    local description="$1"
    shift
    info "$description"
    echo "Command: $*"
    if "$@"; then
        return 0
    fi
    if [[ "$description" == "Preflight check" ]]; then
        print_python_wheel_recovery
    fi
    if [[ "$KEEP_GOING" == "true" ]]; then
        HAD_FAILURE=true
        echo "WARN: command failed but --keep-going is enabled: $description"
        return 0
    fi
    return 1
}

prepare_runtime() {
    load_docker_image_if_present

    if [[ -d "${APP_ROOT}/artifacts" && -f "${APP_ROOT}/docker/install_offline_bundle.sh" ]]; then
        info "Installing offline bundle to ${INSTALL_DIR}"
        chmod +x "${APP_ROOT}/docker/"*.sh 2>/dev/null || true
        (cd "${APP_ROOT}" && ./docker/install_offline_bundle.sh \
            --flink-home "$FLINK_DIR" \
            --install-dir "$INSTALL_DIR" \
            --copy-profiler)
        [[ -x "${INSTALL_DIR}/docker/run_all_apps.sh" ]] || die "installed runtime is missing docker/run_all_apps.sh"
        RUNTIME_ROOT="${INSTALL_DIR}"
        return 0
    fi

    if [[ -f "${APP_ROOT}/docker/run_all_apps.sh" && -f "${APP_ROOT}/docker/server_setup.sh" ]]; then
        info "Preparing full repository runtime"
        chmod +x "${APP_ROOT}/docker/"*.sh 2>/dev/null || true
        (cd "${APP_ROOT}/docker" && ./server_setup.sh --flink-home "$FLINK_DIR" --no-start)
        RUNTIME_ROOT="${APP_ROOT}"
        return 0
    fi

    if [[ -f "${APP_ROOT}/docker/install_offline_bundle.sh" ]]; then
        info "Installing offline bundle to ${INSTALL_DIR}"
        chmod +x "${APP_ROOT}/docker/"*.sh 2>/dev/null || true
        (cd "${APP_ROOT}" && ./docker/install_offline_bundle.sh \
            --flink-home "$FLINK_DIR" \
            --install-dir "$INSTALL_DIR" \
            --copy-profiler)
        [[ -x "${INSTALL_DIR}/docker/run_all_apps.sh" ]] || die "installed runtime is missing docker/run_all_apps.sh"
        RUNTIME_ROOT="${INSTALL_DIR}"
        return 0
    fi

    die "cannot find a runnable ForL0 repository or offline bundle under ${APP_ROOT}"
}

sync_runtime_control_plane() {
    if [[ "$CONTROL_ROOT" != "$APP_ROOT" ]]; then
        info "Syncing current repository control scripts into installed runtime"
        mkdir -p "${RUNTIME_ROOT}/benchmark/config" "${RUNTIME_ROOT}/benchmark/scripts/utils" "${RUNTIME_ROOT}/docker/deploy"

        local script
        for script in \
            clean_results.py \
            generate_report.py \
            run_benchmark.py \
            run_benchset.py \
            run_client_usecase.py \
            run_nexmark.py \
            run_wordcount.py; do
            cp "${CONTROL_ROOT}/benchmark/scripts/${script}" \
                "${RUNTIME_ROOT}/benchmark/scripts/${script}"
        done
        cp "${CONTROL_ROOT}/benchmark/scripts/utils/config.py" \
            "${RUNTIME_ROOT}/benchmark/scripts/utils/config.py"
        cp "${CONTROL_ROOT}/benchmark/config/benchmark.yaml" \
            "${RUNTIME_ROOT}/benchmark/config/benchmark.yaml"
        cp "${CONTROL_ROOT}/docker/run_all_apps.sh" \
            "${RUNTIME_ROOT}/docker/run_all_apps.sh"
        chmod +x "${RUNTIME_ROOT}/docker/run_all_apps.sh"

        if [[ -d "${CONTROL_ROOT}/docker/deploy/nexmark-flink" ]]; then
            mkdir -p "${RUNTIME_ROOT}/docker/deploy/nexmark-flink"
            cp -a "${CONTROL_ROOT}/docker/deploy/nexmark-flink/." \
                "${RUNTIME_ROOT}/docker/deploy/nexmark-flink/"
            chmod +x "${RUNTIME_ROOT}/docker/deploy/nexmark-flink/bin/"*.sh 2>/dev/null || true
        fi
    fi

    local nexmark_jar
    nexmark_jar="$(compgen -G "${CONTROL_ROOT}/docker/deploy/nexmark-flink-*.jar" | head -n 1 || true)"
    if [[ -n "$nexmark_jar" ]]; then
        cp -f "$nexmark_jar" "${RUNTIME_ROOT}/docker/deploy/"
        rm -f "${RUNTIME_ROOT}/docker/deploy/nexmark-flink/lib/"nexmark-flink-*.jar
        cp -f "$nexmark_jar" "${RUNTIME_ROOT}/docker/deploy/nexmark-flink/lib/"
        echo "      ✓ Synced Java 8 NexMark JAR into runtime distribution"
    fi
}

RUNTIME_ROOT=""
prepare_runtime
sync_runtime_control_plane
RUNNER="${RUNTIME_ROOT}/docker/run_all_apps.sh"
[[ -x "$RUNNER" ]] || die "run_all_apps.sh is not executable: $RUNNER"
if [[ "$RESULTS_DIR" != /* ]]; then
    RESULTS_DIR="${APP_ROOT}/${RESULTS_DIR}"
fi
mkdir -p "$RESULTS_DIR"
RESULTS_DIR="$(cd "$RESULTS_DIR" && pwd)"
export FORL0_RESULTS_DIR="$RESULTS_DIR"

info "Runtime summary"
echo "  app root:    ${APP_ROOT}"
echo "  runtime:     ${RUNTIME_ROOT}"
echo "  results:     ${FORL0_RESULTS_DIR}"
echo "  FLINK_HOME:  ${FLINK_DIR}"
echo "  backend:     ${BACKEND}"
echo "  profile:     ${PROFILE_ARGS[*]}"
echo "  pressure:    ${PRESSURE_SCENARIOS}"
if [[ "$RUN_ASCEND_REPRO" == "true" ]]; then
    echo "  workloads:   ${REPRO_WORKLOADS}"
fi
echo "  expected TM: ${EXPECTED_TASKMANAGERS}"
echo "  expected slots: ${EXPECTED_SLOTS}"

COMMON_RUNNER_ARGS=(--expected-taskmanagers "$EXPECTED_TASKMANAGERS" --expected-slots "$EXPECTED_SLOTS")
if [[ "$RESTART_CLUSTER" == "true" ]]; then
    COMMON_RUNNER_ARGS+=(--restart-cluster)
fi
if [[ ${#RUNNER_EXTRA_ARGS[@]} -gt 0 ]]; then
    COMMON_RUNNER_ARGS+=("${RUNNER_EXTRA_ARGS[@]}")
fi

preflight_test="apps"
if [[ "$RUN_NEXMARK_PRESSURE" == "true" && "$RUN_APPS" == "false" && "$RUN_SMOKE" == "false" && "$RUN_ASCEND_REPRO" == "false" ]]; then
    preflight_test="nexmark"
fi
PREFLIGHT_RUNNER_ARGS=("${COMMON_RUNNER_ARGS[@]}")
if [[ "$INITIAL_RESTART_CLUSTER" == "true" && "$RUN_SMOKE$RUN_APPS$RUN_NEXMARK_PRESSURE$RUN_ASCEND_REPRO" == *true* ]]; then
    PREFLIGHT_RUNNER_ARGS+=(--restart-cluster)
fi
run_or_handle_failure "Preflight check" \
    "$RUNNER" --offline --preflight-only --test "$preflight_test" --backend "$BACKEND" "${PREFLIGHT_RUNNER_ARGS[@]}"

if [[ "$RUN_SMOKE" == "true" ]]; then
    run_or_handle_failure "Smoke test: client_usecase contract_baseline" \
        "$RUNNER" --offline --test client_usecase --scenario contract_baseline \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    run_or_handle_failure "Smoke test: NexMark q18 Java/runtime path" \
        "$RUNNER" --offline --test nexmark --scenario forl0_tps_probe --query q18 \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
fi

if [[ "$RUN_APPS" == "true" ]]; then
    run_or_handle_failure "Contract app W01: WordCount contract_baseline" \
        "$RUNNER" --offline --test wordcount --scenario contract_baseline \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    run_or_handle_failure "Contract app N01: NexMark contract_baseline" \
        "$RUNNER" --offline --test nexmark --scenario contract_baseline \
        --query q4,q5,q8,q9,q11,q18,q19,q20 \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    run_or_handle_failure "Contract app C01: Client Usecase contract_baseline" \
        "$RUNNER" --offline --test client_usecase --scenario contract_baseline \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
fi

if [[ "$RUN_NEXMARK_PRESSURE" == "true" ]]; then
    IFS=',' read -r -a pressure_scenarios <<< "$PRESSURE_SCENARIOS"
    for scenario in "${pressure_scenarios[@]}"; do
        scenario="$(printf '%s' "$scenario" | xargs)"
        [[ -n "$scenario" ]] || continue
        query_args=()
        if [[ "$QUERIES_EXPLICIT" == "true" || "$scenario" == "forl0_no_full_gc_allq_pressure" ]]; then
            query_args=(--query "$QUERIES")
        fi
        run_or_handle_failure "NexMark tuned pressure sweep: ${scenario}" \
            "$RUNNER" --offline --test nexmark --scenario "$scenario" \
            --backend "$BACKEND" "${query_args[@]}" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    done
fi

if [[ "$RUN_ASCEND_REPRO" == "true" ]]; then
    run_log_dir="${FORL0_RESULTS_DIR}/run_logs"
    mkdir -p "$run_log_dir"
    manifest="${run_log_dir}/ascend_reproduction_$(date '+%Y%m%d_%H%M%S').tsv"
    {
        printf "# run_id=%s\n" "${FORL0_RUN_ID:-unassigned}"
        printf "# run_started_epoch=%s\n" "${FORL0_RUN_STARTED_EPOCH:-unassigned}"
        printf "id\tname\tdescription\n"
        for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
            IFS='|' read -r id name description <<< "$entry"
            if workload_selected "$id"; then
                printf "%s\t%s\t%s\n" "$id" "$name" "$description"
            fi
        done
    } > "$manifest"
    echo "Ascend reproduction manifest: $manifest"

    ran_any=false
    for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
        IFS='|' read -r id _ <<< "$entry"
        if workload_selected "$id"; then
            ran_any=true
            run_ascend_workload "$id"
        fi
    done
    [[ "$ran_any" == "true" ]] || die "no Ascend reproduction workloads selected: $REPRO_WORKLOADS"
fi

if [[ "$RUN_REPORT" == "true" ]]; then
    run_or_handle_failure "Generate benchmark HTML report" \
        "$RUNNER" --offline --report-only --no-profile
fi

info "Done"
echo "Report:"
echo "  ${FORL0_RESULTS_DIR}/reports/benchmark_report.html"
echo "Raw results:"
echo "  ${FORL0_RESULTS_DIR}/raw/"
echo "NexMark runs:"
echo "  ${FORL0_RESULTS_DIR}/nexmark_*/"
if [[ "$HAD_FAILURE" == "true" ]]; then
    echo "ERROR: one or more workloads failed; inspect ${FORL0_RESULTS_DIR}/run_logs/FAILED_*" >&2
    exit 1
fi
