#!/usr/bin/env bash
################################################################################
# ForL0 offline app launcher
#
# One command on the offline server:
#   ./forl0-offline-app.sh --flink-home /path/to/flink-1.20.3
#
# It works in either layout:
#   1. full repository root
#   2. offline bundle root generated by docker/package_offline_bundle.sh
################################################################################

set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLINK_DIR="${FLINK_HOME:-}"
INSTALL_DIR="${HOME}/forl0-runtime"
BACKEND="all"
QUERIES="q4,q5,q8,q9,q11,q18,q19,q20"
QUERIES_EXPLICIT=false
PRESSURE_SCENARIOS="forl0_tps_probe"
REPRO_WORKLOADS="all"
RUN_SMOKE=true
RUN_APPS=true
RUN_NEXMARK_PRESSURE=false
RUN_ASCEND_REPRO=false
RUN_REPORT=true
PROFILE_ARGS=(--no-profile)
SKIP_DOCKER_LOAD=false
KEEP_GOING=false
RESTART_CLUSTER=false
LIST_WORKLOADS=false
EXPECTED_TASKMANAGERS="${FORL0_EXPECTED_TASKMANAGERS:-2}"
EXPECTED_SLOTS="${FORL0_EXPECTED_SLOTS:-8}"
RUNNER_EXTRA_ARGS=()

ASCEND_REPRO_WORKLOADS=(
    "N01|nexmark_q18_hashmap_isolated|NexMark q18 TPS probe, HashMap baseline, isolated cluster"
    "N02|nexmark_q18_forl0_isolated|NexMark q18 TPS probe, ForL0 stable winner, isolated cluster"
    "N03|nexmark_q19_hashmap_isolated|NexMark q19 TPS probe, HashMap baseline, isolated cluster"
    "N04|nexmark_q19_forl0_isolated|NexMark q19 TPS probe, ForL0 stable winner, isolated cluster"
)

usage() {
    cat <<'EOF'
ForL0 offline app launcher

Usage:
  ./forl0-offline-app.sh --flink-home /path/to/flink-1.20.3 [options]

Common options:
  --flink-home PATH       Flink installation directory. Can also use FLINK_HOME.
  --install-dir PATH      Runtime install dir when running from an offline bundle.
                          Default: ~/forl0-runtime
  --backend NAME          all / forl0 / hashmap. Default: all
  --queries LIST          Override NexMark query list for pressure scenarios.
                          By default, each tuned pressure scenario uses its own
                          query list from benchmark.yaml; allq uses q4,q5,q8,q9,q11,q18,q19,q20.
  --pressure-scenarios LIST
                          Comma-separated NexMark pressure scenarios for --full.
                          Default: forl0_tps_probe. Deep no-Full-GC pressure
                          scenarios are opt-in because they can OOM 16GB TMs.
  --workloads LIST        Run selected numbered Ascend reproduction workloads.
                          Example: --workloads N01,N02
  --list-workloads        Print numbered Ascend reproduction workloads and exit.

Run modes:
  --smoke-only            Install + preflight + short client smoke test only.
  --apps-only             Install + preflight + contract apps only.
  --full                  Also run the stable NexMark TPS probe after apps.
  --pressure-only         Install + preflight + stable NexMark TPS probe only.
  --reproduce-ascend      Run the numbered Ascend reproduction suite.
  --report-only           Do not run experiments; regenerate HTML report only.
  --no-report             Do not generate the final HTML report.
  --with-profile          Enable default CPU profiling. Default is --no-profile.
  --profile MODE          Enable a specific profile mode, e.g. cpu/cache/uarch.

Operational options:
  --skip-docker-load      Do not import docker/images/eclipse-temurin-8-jre.tar*.
  --keep-going            Continue to report generation after a benchmark failure.
  --restart-cluster       Restart the benchmark Flink cluster before running.
  --expected-taskmanagers N
                          Required registered TaskManager count before experiments.
                          Default: 2
  --expected-slots N      Required total slot count before experiments. Default: 8
  -h, --help              Show this help.
EOF
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

info() {
    echo ""
    echo "==> $*"
}

list_ascend_workloads() {
    printf "%-4s  %-36s  %s\n" "ID" "Name" "Description"
    printf "%-4s  %-36s  %s\n" "----" "------------------------------------" "-----------"
    local entry id name description
    for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
        IFS='|' read -r id name description <<< "$entry"
        printf "%-4s  %-36s  %s\n" "$id" "$name" "$description"
    done
}

workload_selected() {
    local id="$1"
    local requested token
    local -a selected_workloads
    requested="$(printf '%s' "$REPRO_WORKLOADS" | tr '[:lower:]' '[:upper:]')"
    [[ "$requested" == "ALL" ]] && return 0
    IFS=',' read -r -a selected_workloads <<< "$requested"
    for token in "${selected_workloads[@]}"; do
        token="$(printf '%s' "$token" | xargs)"
        [[ "$token" == "$id" ]] && return 0
    done
    return 1
}

validate_repro_workloads() {
    local requested token entry id found
    local -a selected_workloads
    requested="$(printf '%s' "$REPRO_WORKLOADS" | tr '[:lower:]' '[:upper:]')"
    [[ "$requested" == "ALL" ]] && return 0
    IFS=',' read -r -a selected_workloads <<< "$requested"
    for token in "${selected_workloads[@]}"; do
        token="$(printf '%s' "$token" | xargs)"
        [[ -n "$token" ]] || continue
        found=false
        for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
            IFS='|' read -r id _ <<< "$entry"
            if [[ "$id" == "$token" ]]; then
                found=true
                break
            fi
        done
        if [[ "$found" != "true" ]]; then
            echo "ERROR: unknown workload id: $token" >&2
            echo "" >&2
            list_ascend_workloads >&2
            exit 1
        fi
    done
}

workload_name() {
    local id="$1"
    local entry wid name description
    for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
        IFS='|' read -r wid name description <<< "$entry"
        if [[ "$wid" == "$id" ]]; then
            printf '%s' "$name"
            return 0
        fi
    done
    printf '%s' "$id"
}

run_ascend_workload() {
    local id="$1"
    local name
    name="$(workload_name "$id")"
    local args=()

    case "$id" in
        N01) args=(--test nexmark --scenario forl0_tps_probe --query q18 --backend hashmap) ;;
        N02) args=(--test nexmark --scenario forl0_tps_probe --query q18 --backend forl0) ;;
        N03) args=(--test nexmark --scenario forl0_tps_probe --query q19 --backend hashmap) ;;
        N04) args=(--test nexmark --scenario forl0_tps_probe --query q19 --backend forl0) ;;
        *) die "unknown Ascend reproduction workload id: $id" ;;
    esac

    run_or_handle_failure "Ascend reproduction ${id}: ${name}" \
        "$RUNNER" --offline "${args[@]}" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --flink-home)
            FLINK_DIR="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --backend)
            BACKEND="$2"
            shift 2
            ;;
        --queries)
            QUERIES="$2"
            QUERIES_EXPLICIT=true
            shift 2
            ;;
        --pressure-scenarios)
            PRESSURE_SCENARIOS="$2"
            shift 2
            ;;
        --workloads)
            REPRO_WORKLOADS="$2"
            RUN_ASCEND_REPRO=true
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            shift 2
            ;;
        --list-workloads)
            LIST_WORKLOADS=true
            shift
            ;;
        --smoke-only)
            RUN_SMOKE=true
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            shift
            ;;
        --apps-only)
            RUN_SMOKE=false
            RUN_APPS=true
            RUN_NEXMARK_PRESSURE=false
            shift
            ;;
        --full)
            RUN_SMOKE=true
            RUN_APPS=true
            RUN_NEXMARK_PRESSURE=true
            shift
            ;;
        --pressure-only)
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=true
            shift
            ;;
        --reproduce-ascend)
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            RUN_ASCEND_REPRO=true
            shift
            ;;
        --report-only)
            RUN_SMOKE=false
            RUN_APPS=false
            RUN_NEXMARK_PRESSURE=false
            RUN_REPORT=true
            shift
            ;;
        --no-report)
            RUN_REPORT=false
            shift
            ;;
        --with-profile)
            PROFILE_ARGS=(--profile cpu)
            shift
            ;;
        --profile)
            PROFILE_ARGS=(--profile "$2")
            shift 2
            ;;
        --skip-docker-load)
            SKIP_DOCKER_LOAD=true
            shift
            ;;
        --keep-going)
            KEEP_GOING=true
            shift
            ;;
        --restart-cluster)
            RESTART_CLUSTER=true
            shift
            ;;
        --expected-taskmanagers)
            EXPECTED_TASKMANAGERS="$2"
            shift 2
            ;;
        --expected-slots)
            EXPECTED_SLOTS="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            RUNNER_EXTRA_ARGS+=("$1")
            shift
            ;;
    esac
done

if [[ "$LIST_WORKLOADS" == "true" ]]; then
    list_ascend_workloads
    exit 0
fi

validate_repro_workloads

if [[ "$RUN_ASCEND_REPRO" == "true" ]]; then
    RESTART_CLUSTER=true
fi

case "$BACKEND" in
    all|forl0|hashmap) ;;
    *) die "--backend must be all, forl0, or hashmap: $BACKEND" ;;
esac

[[ -n "$FLINK_DIR" ]] || die "missing --flink-home PATH or FLINK_HOME"
[[ -d "$FLINK_DIR" ]] || die "FLINK_HOME does not exist: $FLINK_DIR"
export FLINK_HOME="$FLINK_DIR"

detect_docker_cmd() {
    if docker ps >/dev/null 2>&1; then
        echo "docker"
        return 0
    fi
    if sudo -n docker ps >/dev/null 2>&1; then
        echo "sudo -n docker"
        return 0
    fi
    return 1
}

load_docker_image_if_present() {
    [[ "$SKIP_DOCKER_LOAD" == "false" ]] || return 0

    local docker_cmd
    docker_cmd="$(detect_docker_cmd || true)"
    if [[ -z "$docker_cmd" ]]; then
        echo "WARN: docker is unavailable for current user; standalone fallback may be used."
        return 0
    fi

    if $docker_cmd image inspect eclipse-temurin:8-jre >/dev/null 2>&1; then
        echo "Docker image already present: eclipse-temurin:8-jre"
        return 0
    fi

    local image_file=""
    for candidate in \
        "${APP_ROOT}/docker/images/eclipse-temurin-8-jre.tar.gz" \
        "${APP_ROOT}/docker/images/eclipse-temurin-8-jre.tar" \
        "${APP_ROOT}/eclipse-temurin-8-jre.tar.gz" \
        "${APP_ROOT}/eclipse-temurin-8-jre.tar"; do
        if [[ -f "$candidate" ]]; then
            image_file="$candidate"
            break
        fi
    done

    if [[ -n "$image_file" ]]; then
        info "Loading Docker image: $image_file"
        $docker_cmd load -i "$image_file"
    else
        echo "WARN: docker image is not present in bundle; docker_run.sh may fail offline."
    fi
}

run_or_handle_failure() {
    local description="$1"
    shift
    info "$description"
    echo "Command: $*"
    if "$@"; then
        return 0
    fi
    if [[ "$KEEP_GOING" == "true" ]]; then
        echo "WARN: command failed but --keep-going is enabled: $description"
        return 0
    fi
    return 1
}

prepare_runtime() {
    load_docker_image_if_present

    if [[ -d "${APP_ROOT}/artifacts" && -f "${APP_ROOT}/docker/install_offline_bundle.sh" ]]; then
        info "Installing offline bundle to ${INSTALL_DIR}"
        chmod +x "${APP_ROOT}/docker/"*.sh 2>/dev/null || true
        (cd "${APP_ROOT}" && ./docker/install_offline_bundle.sh \
            --flink-home "$FLINK_DIR" \
            --install-dir "$INSTALL_DIR" \
            --copy-profiler)
        [[ -x "${INSTALL_DIR}/docker/run_all_apps.sh" ]] || die "installed runtime is missing docker/run_all_apps.sh"
        RUNTIME_ROOT="${INSTALL_DIR}"
        return 0
    fi

    if [[ -f "${APP_ROOT}/docker/run_all_apps.sh" && -f "${APP_ROOT}/docker/server_setup.sh" ]]; then
        info "Preparing full repository runtime"
        chmod +x "${APP_ROOT}/docker/"*.sh 2>/dev/null || true
        (cd "${APP_ROOT}/docker" && ./server_setup.sh --flink-home "$FLINK_DIR" --no-start)
        RUNTIME_ROOT="${APP_ROOT}"
        return 0
    fi

    if [[ -f "${APP_ROOT}/docker/install_offline_bundle.sh" ]]; then
        info "Installing offline bundle to ${INSTALL_DIR}"
        chmod +x "${APP_ROOT}/docker/"*.sh 2>/dev/null || true
        (cd "${APP_ROOT}" && ./docker/install_offline_bundle.sh \
            --flink-home "$FLINK_DIR" \
            --install-dir "$INSTALL_DIR" \
            --copy-profiler)
        [[ -x "${INSTALL_DIR}/docker/run_all_apps.sh" ]] || die "installed runtime is missing docker/run_all_apps.sh"
        RUNTIME_ROOT="${INSTALL_DIR}"
        return 0
    fi

    die "cannot find a runnable ForL0 repository or offline bundle under ${APP_ROOT}"
}

RUNTIME_ROOT=""
prepare_runtime
RUNNER="${RUNTIME_ROOT}/docker/run_all_apps.sh"
[[ -x "$RUNNER" ]] || die "run_all_apps.sh is not executable: $RUNNER"

info "Runtime summary"
echo "  app root:    ${APP_ROOT}"
echo "  runtime:     ${RUNTIME_ROOT}"
echo "  FLINK_HOME:  ${FLINK_DIR}"
echo "  backend:     ${BACKEND}"
echo "  profile:     ${PROFILE_ARGS[*]}"
echo "  pressure:    ${PRESSURE_SCENARIOS}"
if [[ "$RUN_ASCEND_REPRO" == "true" ]]; then
    echo "  workloads:   ${REPRO_WORKLOADS}"
fi
echo "  expected TM: ${EXPECTED_TASKMANAGERS}"
echo "  expected slots: ${EXPECTED_SLOTS}"

COMMON_RUNNER_ARGS=(--expected-taskmanagers "$EXPECTED_TASKMANAGERS" --expected-slots "$EXPECTED_SLOTS")
if [[ "$RESTART_CLUSTER" == "true" ]]; then
    COMMON_RUNNER_ARGS+=(--restart-cluster)
fi
if [[ ${#RUNNER_EXTRA_ARGS[@]} -gt 0 ]]; then
    COMMON_RUNNER_ARGS+=("${RUNNER_EXTRA_ARGS[@]}")
fi

preflight_test="apps"
run_or_handle_failure "Preflight check" \
    "$RUNNER" --offline --preflight-only --test "$preflight_test" --backend "$BACKEND" "${COMMON_RUNNER_ARGS[@]}"

if [[ "$RUN_SMOKE" == "true" ]]; then
    run_or_handle_failure "Smoke test: client_usecase contract_baseline" \
        "$RUNNER" --offline --test client_usecase --scenario contract_baseline \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
fi

if [[ "$RUN_APPS" == "true" ]]; then
    run_or_handle_failure "Contract app W01: WordCount contract_baseline" \
        "$RUNNER" --offline --test wordcount --scenario contract_baseline \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    run_or_handle_failure "Contract app N01: NexMark contract_baseline" \
        "$RUNNER" --offline --test nexmark --scenario contract_baseline \
        --query q4,q5,q8,q9,q11,q18,q19,q20 \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    run_or_handle_failure "Contract app C01: Client Usecase contract_baseline" \
        "$RUNNER" --offline --test client_usecase --scenario contract_baseline \
        --backend "$BACKEND" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
fi

if [[ "$RUN_NEXMARK_PRESSURE" == "true" ]]; then
    IFS=',' read -r -a pressure_scenarios <<< "$PRESSURE_SCENARIOS"
    for scenario in "${pressure_scenarios[@]}"; do
        scenario="$(printf '%s' "$scenario" | xargs)"
        [[ -n "$scenario" ]] || continue
        query_args=()
        if [[ "$QUERIES_EXPLICIT" == "true" || "$scenario" == "forl0_no_full_gc_allq_pressure" ]]; then
            query_args=(--query "$QUERIES")
        fi
        run_or_handle_failure "NexMark tuned pressure sweep: ${scenario}" \
            "$RUNNER" --offline --test nexmark --scenario "$scenario" \
            --backend "$BACKEND" "${query_args[@]}" "${PROFILE_ARGS[@]}" --no-report "${COMMON_RUNNER_ARGS[@]}"
    done
fi

if [[ "$RUN_ASCEND_REPRO" == "true" ]]; then
    run_log_dir="${RUNTIME_ROOT}/benchmark/results/run_logs"
    mkdir -p "$run_log_dir"
    manifest="${run_log_dir}/ascend_reproduction_$(date '+%Y%m%d_%H%M%S').tsv"
    {
        printf "id\tname\tdescription\n"
        for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
            IFS='|' read -r id name description <<< "$entry"
            if workload_selected "$id"; then
                printf "%s\t%s\t%s\n" "$id" "$name" "$description"
            fi
        done
    } > "$manifest"
    echo "Ascend reproduction manifest: $manifest"

    ran_any=false
    for entry in "${ASCEND_REPRO_WORKLOADS[@]}"; do
        IFS='|' read -r id _ <<< "$entry"
        if workload_selected "$id"; then
            ran_any=true
            run_ascend_workload "$id"
        fi
    done
    [[ "$ran_any" == "true" ]] || die "no Ascend reproduction workloads selected: $REPRO_WORKLOADS"
fi

if [[ "$RUN_REPORT" == "true" ]]; then
    run_or_handle_failure "Generate benchmark HTML report" \
        "$RUNNER" --offline --report-only --no-profile
fi

info "Done"
echo "Report:"
echo "  ${RUNTIME_ROOT}/benchmark/results/reports/benchmark_report.html"
echo "Raw results:"
echo "  ${RUNTIME_ROOT}/benchmark/results/raw/"
echo "NexMark runs:"
echo "  ${RUNTIME_ROOT}/benchmark/results/nexmark_*/"
